linuxpath: "data/file_to_search.txt"
ssl_enabled: True
reread: True
ca_bundle_file: "certs/ca.pem"
server_certfile: "certs/server.crt"
server_keyfile: "certs/server.key"
client_certfile: "certs/client.crt"
client_keyfile: "certs/client.key"
search_algorithm: "mmap"
search_benchmark_csv: "utils/search_benchmark_results.csv"
load_test_csv: "utils/load_test_results.csv"
server_host: "127.0.0.1"
server_port: 5000
search_term: "Stephen is overly talented"
temp_file_dir: "tests/temp_files"
results_dir: "utils"
client_timeout_time: 30
log_dir: "/var/log"